/* empty css                      */import{S as c,N as g,P as w}from"./assets/vendor-BSBkFbx1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();c.use([g,w]);function m(o){if(!o)return;o.destroy(!0,!0);const t=o.el;t==null||t.removeAttribute("style");const n=t==null?void 0:t.querySelector(".swiper-wrapper");n==null||n.removeAttribute("style"),t==null||t.querySelectorAll(".swiper-slide").forEach(i=>{i.removeAttribute("style")})}function p({rootSelector:o,prevEl:t,nextEl:n,paginationEl:i}){const e=document.querySelector(o);if(!e)return;const r=e.querySelector(".swiper");if(!r)return;let s=null;const l=window.matchMedia("(min-width: 1440px)"),d=()=>{s||(s=new c(r,{slidesPerView:1,spaceBetween:16,speed:450,loop:!1,grabCursor:!0,navigation:{prevEl:t,nextEl:n},pagination:{el:i,clickable:!0,type:"bullets"}}))},f=()=>{s&&(m(s),s=null)},a=()=>{l.matches?f():d()};a();const u=()=>a();l.addEventListener?l.addEventListener("change",u):l.addListener(u)}function h({rootSelector:o,prevEl:t,nextEl:n,paginationEl:i}){const e=document.querySelector(o);if(!e)return;const r=e.querySelector(".swiper");r&&(r.classList.contains("swiper-initialized")||new c(r,{slidesPerView:1,spaceBetween:16,speed:450,loop:!1,grabCursor:!0,navigation:{prevEl:t,nextEl:n},pagination:{el:i,clickable:!0,type:"bullets"}}))}p({rootSelector:".connect-swiper",prevEl:".connect-prev",nextEl:".connect-next",paginationEl:".connect-pagination"});p({rootSelector:".design-swiper",prevEl:".design-prev",nextEl:".design-next",paginationEl:".design-pagination"});h({rootSelector:".puzzle-swiper",prevEl:".puzzle-prev",nextEl:".puzzle-next",paginationEl:".puzzle-pagination"});document.querySelectorAll(".faq-acc-el-trigger").forEach(o=>{o.addEventListener("click",()=>{const t=o.closest(".faq-acc-el"),n=t.querySelector(".faq-acc-el-descr-frame"),i=o.querySelector("svg"),e=t.classList.contains("open"),r=`
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4.1665 10H15.8332" stroke="#151515" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M10 4.1665V15.8332" stroke="#151515" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,s=`
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4.1665 10H15.8332" stroke="#151515" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M10 4.1665V15.8332" stroke="#151515" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;e?(t.classList.remove("open"),n.style.maxHeight="0",i.outerHTML=r):(t.classList.add("open"),n.style.maxHeight=n.scrollHeight+"px",i.outerHTML=s)})});
//# sourceMappingURL=index.js.map
